name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.2.6
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Load OpenSSL ripemd160
      run: |
        sed -i '/^\default = default_sect/a legacy = legacy_sect' /etc/ssl/openssl.cnf
        sed -i '/^\[default_sect\]/a activate = 1' /etc/ssl/openssl.cnf
        echo "[legacy_sect]" >> /etc/ssl/openssl.cnf
        echo "activate = 1" >> /etc/ssl/openssl.cnf

    - name: Install dependencies
      run: |
        bundle config set without 'development'
        bundle config path vendor/bundle
        bundle install --jobs=9 --retry=2 --quiet

    - name: Setup test database
      run: |
        cp config/config.yml.sample config/config.yml
        cp config/database.yml.sample config/database.yml
        bin/rails db:migrate RAILS_ENV=test

    - name: Rubocop
      run: |
        bundle exec rubocop

    - name: Run RSpec
      run: |
        bundle exec rake spec

    - name: Run Cucumber
      run: |
        bundle exec rake cucumber
